### PR TITLE
Here are the list of changes inside the taper monkey script

### PR DESCRIPTION
**Pull request by Nthompson096**
Have 3:
One for just mobile (historic)
One for just desktop (historic)
One for mobile and desktop use (recommended you use this one)
Feel free to use [FaceCheck URL Extractor with Ratings (Desktop and Mobile)-2.1.0.user.js ](https://github.com/Nthompson096/facecheck.id-results-extractor-mobile/blob/main/FaceCheck%20URL%20Extractor%20with%20Ratings%20(Desktop%20and%20Mobile)-2.1.0.user.js) as stated in issue #2

### CODE REVIEW

**Comment by Nthompson096** [comment]
New to creating a pull request.

**Comment by Nthompson096** [comment]
Also had shortened the script; instead of 144 lines of code it's just 66 for the Desktop and mobile variant.

**Comment by vin3110** [comment]
> Also had shortened the script; instead of 144 lines of code it's just 131 for the Desktop and mobile variant.

I'll take a quick look and merge ur fork <3. I'm new to forks and stuff so forgive me if im a bit slow lol

**Comment by Nthompson096** [comment]
Take your time; be sure to try this out in your browser in both desktop and mobile mode.

**Pull request merged**
